### ISSUE TITLE
Custom Fields - Theme Options: Header tab, It is not mentioned in the scope to create ACFs for Social Media, Email and Phone label

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Frigmac#3]
Social Media, Email and Phone will be from Business Details, once the field(s) is empty, it's value and label should be hidden.
![image](https://cloud.githubusercontent.com/assets/12888048/15564651/0b568c74-2347-11e6-88e6-b03a60d46c86.png)

**Comment by jewelcantuba** [comment]
Scope error.
